### ISSUE TITLE
Bookmark for C projects under Contents in Readme is not defined

### ISSUE THREAD

**Issue by dpavankvarma** [IonicaBizau/made-in-bosnia#7]
![bookmarkissue](https://user-images.githubusercontent.com/25107841/34071793-42225f14-e2a2-11e7-8558-7e520b23ddb6.gif)

**Comment by sake92** [comment]
@IonicaBizau btw, I wanted to fix URL for `@adnanrahic/securing-restful-apis-with-jwt` repo in README, but **it does not exist** in `package.json`. Almost if merge didn't succeed or something? xD
